### PR TITLE
Add version-listing tool

### PR DESCRIPTION
**Pull request by jrising**
Finds the installed module versions and git repository hashes of a set of modules, to be included in output file dependencies.

### CODE REVIEW

**Comment by jgerardsimcock** [comment]
I agree keeping track of dependencies is useful. And is it possible to specify this ahead of time with a requirements.txt?

**Comment by jrising** [comment]
I think there are a few problems with this idea:
 - The requirements.txt will not specify the most important dependency for any file, which is the hash for the repo that generated it (that is, the one that contains both the script that generated the file and the requirements.txt file).
 - Generally, a repository will generate multiple files (e.g., like socioeconomics does), and while the requirements.txt file needs to specify the libraries needed for all of these, each file should only record the libraries that are actually necessary for it.
 - Even if we version all of our repos so that they could be in a requirements.txt file, there are plenty of reasonable cases where the version we want to use will just be the master development branch.

**Comment by delgadom** [comment]
What about tagging the commit that produced major outputs and then sticking the repo and tag ID in the metadata? That seems like the "industry standard" way to do this for non-released packages, right?

Then you have the package dependencies in the repo, and then include in the output file's metadata the repo url, the tag ID, and the data dependencies. That provides exactly how much information you need to reproduce the results, right?

**Comment by jrising** [comment]
The goal of this was to make the process of recording accurate dependencies easier.  Unless I misunderstand it, your proposal seems strictly less easy than filling it out by hand and equally error-prone.

**Comment by jrising** [comment]
Thanks!  I shared the changes you made with Jong-kai.

**Pull request merged**
